name: myenv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _py-xgboost-mutex=2.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - flake8=7.1.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - imbalanced-learn=0.12.3
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.31.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxgboost=2.1.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.1
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pyparsing=3.2.0
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=25.1.1
  - readline=8.2
  - scikit-learn=1.5.2
  - scipy=1.15.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xgboost=2.1.1
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /opt/anaconda3/envs/myenv
